# Generated by Django 3.1.12 on 2025-06-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramingoApp', '0004_traininganswer_trainingmodule_trainingprogress_trainingquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
